#import "../template.typ": parec

== Exercises

#parec[
  1. The functionality of the `SpotLight` could be replicated by using a
    suitable image in conjunction with the
    #link("../Light_Sources/Point_Lights.html#ProjectionLight")[`ProjectionLight`]
    or
    #link("../Light_Sources/Point_Lights.html#GoniometricLight")[`GoniometricLight`];.
    Discuss the advantages and disadvantages of providing this specific
    functionality separately with the `SpotLight` class.
][
  1. `SpotLight` 的功能可以通过结合使用合适的图像和 #link("../Light_Sources/Point_Lights.html#ProjectionLight")[`ProjectionLight`] 或 #link("../Light_Sources/Point_Lights.html#GoniometricLight")[`GoniometricLight`] 来复制。讨论单独提供 `SpotLight` 类的这种特定功能的优缺点。
]

#parec[
  + Modify the
    #link("../Light_Sources/Point_Lights.html#ProjectionLight")[`ProjectionLight`]
    to also support orthographic projections. This variant is particularly
    useful even without an image map, since it gives a directional light
    source with a beam of user-defined extent.
][
  #block[
    #set enum(numbering: "1.", start: 2)
    + 修改
      #link("../Light_Sources/Point_Lights.html#ProjectionLight")[`ProjectionLight`]
      以支持正交投影。即使在没有图像贴图的情况下，这种变体也特别有用，因为它提供了具有用户定义范围的定向光源。
  ]
]

#parec[
  #block[
    #set enum(numbering: "1.", start: 3)
    + The current light source implementations do not support animated
      transformations. Modify `pbrt` to include this functionality and
      render images showing off the effect of animating light positions.
      Note that if you would like to use the
      #link("../Light_Sources/Light_Sampling.html#BVHLightSampler")[`BVHLightSampler`]
      with animated light sources, it will require substantial
      modifications.
  ]
][
  #block[
    #set enum(numbering: "1.", start: 3)
    + 当前的光源实现不支持动画变换。修改 `pbrt`
      以包含此功能并渲染图像以展示动画光源位置的效果。请注意，如果您希望使用
      #link("../Light_Sources/Light_Sampling.html#BVHLightSampler")[`BVHLightSampler`]
      与动画光源一起使用，则需要进行大量修改。
  ]
]

#parec[
  #block[
    #set enum(numbering: "1.", start: 4)
    + Implement an area light that generalizes the
      #link("../Light_Sources/Area_Lights.html#DiffuseAreaLight")[`DiffuseAreaLight`]
      to support directionally varying emitted radiance. You might, for
      example, allow focusing the light by computing the cosine of the
      outgoing direction and the surface normal and raising it to some
      power. Derive a model such that the total power of the light is left
      unchanged as the directional distribution of emitted radiance varies
      and update the light's `SampleLe()` methods for sampling rays leaving
      the light to account for the emission distribution. Discuss the
      implications of your approach for sampling via `SampleLi()`; should
      that method be aware of the changed directional distribution?
  ]
][
  #block[
    #set enum(numbering: "1.", start: 4)
    + 实现一个广义的区域光，使其支持方向变化的辐射度发射，类似于
      #link("../Light_Sources/Area_Lights.html#DiffuseAreaLight")[`DiffuseAreaLight`];。例如，您可以通过计算出射方向与表面法线的余弦并将其提升到某个幂次来聚焦光线。推导出一个模型公式，使得随着辐射度发射的方向分布变化，光的总功率保持不变，并更新光的
      `SampleLe()`
      方法以便对离开光的光线进行采样以考虑发射分布。讨论您的方法对通过
      `SampleLi()` 采样的影响；该方法是否应该意识到方向分布的变化？
  ]
]

#parec[
  #block[
    #set enum(numbering: "1.", start: 5)
    + Read some of the papers in the "Further Reading" section that discuss
      the shadow cache, and add this optimization to `pbrt`. Measure how
      much it speeds up the system for a variety of scenes. What techniques
      can you come up with that make it work better in the presence of
      multiple levels of reflection?
  ]
][
  #block[
    #set enum(numbering: "1.", start: 5)
    + 阅读“进一步阅读”部分中讨论阴影缓存的论文，并将此优化添加到
      `pbrt`。测量它在各种场景中对系统加速的效果。您能想到哪些技术可以使其在存在多个反射层时更好地工作？
  ]
]

#parec[
  #block[
    #set enum(numbering: "1.", start: 6)
    + One of the advantages of the linearity assumption in radiometry is
      that the final image of a scene is the same as the sum of individual
      images that account for each light source's contribution (assuming a
      floating-point image file format is used that does not clip pixel
      radiance values). An implication of this property is that if a
      renderer creates a separate image for each light source, it is
      possible to write interactive lighting design tools that make it
      possible to quickly see the effects of scaling the contributions of
      individual lights in the scene without needing to re-render it from
      scratch. Instead, a light's individual image can be scaled and the
      final image regenerated by summing all the light images again. (This
      technique was first applied for opera lighting design by Dorsey,
      Sillion, and Greenberg (1991).) Modify `pbrt` to output a separate
      image for each of the lights in the scene, and write an interactive
      lighting design tool that uses them in this manner.
  ]
][
  #block[
    #set enum(numbering: "1.", start: 6)
    + 辐射度线性假设的一个优点是场景的最终图像与考虑每个光源贡献的单个图像的总和相同（假设使用的浮点图像文件格式不会裁剪像素辐射度值）。这一特性的一个含义是，如果渲染器为每个光源创建单独的图像，则可以编写交互式照明设计工具，使其能够快速查看缩放场景中各个光源贡献的效果，而无需从头开始重新渲染。相反，可以调整光源的单个图像的比例，并通过再次求和所有光源图像来重新生成最终图像。（这种技术最早由
      Dorsey、Sillion 和 Greenberg（1991）应用于歌剧照明设计。）修改 `pbrt`
      以输出场景中每个光源的单独图像，并编写一个使用这些图像的交互式照明设计工具。
  ]
]

#parec[
  #block[
    #set enum(numbering: "1.", start: 7)
    + Read the paper by Velázquez-Armendáriz et al.~(2015), and implement
      their method for efficiently rendering scenes with complex light
      sources. Create or find models of a few complex lights that include
      many shapes that exhibit specular reflection or transmission in order
      to evaluate your implementation.
  ]
][
  #block[
    #set enum(numbering: "1.", start: 7)
    + 阅读 Velázquez-Armendáriz
      等人（2015）的论文，并实现他们的方法以有效渲染具有复杂光源的场景。创建或寻找一些复杂光源的模型，这些光源包含许多表现出镜面反射或透射的形状，以评估您的实现。
  ]
]

#parec[
  #block[
    #set enum(numbering: "1.", start: 8)
    + Generalize the
      #link("../Light_Sources/Infinite_Area_Lights.html#PortalImageInfiniteLight")[`PortalImageInfiniteLight`]
      to allow the specification of multiple portals. Note that multiple
      coplanar portals can be supported without resampling the environment
      map, but non-coplanar portals will require multiple copies of it. As
      noted by Bitterli et al.~(2015), the summed area table representation
      makes it easy to compute the total power passing through a portal
      given a receiving point. Modify your implementation to use the
      relative power of multiple portals as a sampling distribution to
      choose which portal to sample. Render images that show the benefit of
      this improvement.
  ]
][
  #block[
    #set enum(numbering: "1.", start: 8)
    + 将
      #link("../Light_Sources/Infinite_Area_Lights.html#PortalImageInfiniteLight")[`PortalImageInfiniteLight`]
      泛化以允许指定多个门户。请注意，多个共面的门户可以支持而无需重新采样环境贴图，但非共面的门户将需要其多份副本。如
      Bitterli
      等人（2015）所述，累加面积表表示使得可以轻松计算给定接收点的通过门户的总功率。修改您的实现以使用多个门户的相对功率作为采样分布来选择要采样的门户。渲染显示此改进好处的图像。
  ]
]

#parec[
  #block[
    #set enum(numbering: "1.", start: 9)
    + Sampling wavelengths according to the XYZ matching functions is a
      reasonable approach for many scenes, though if the light sources in
      the scene have highly peaked spectra (as, for example, many
      fluorescent lights do), error may be reduced by instead sampling
      wavelengths according to the lights' spectral distributions. Implement
      this approach and compare the results to `pbrt`'s current wavelength
      sampling implementation using a variety of spectral emission profiles.
      How much does the alternative sampling strategy help in the best case
      versus the worst case? Can you find a way to improve the results
      further by applying multiple importance sampling?
  ]
][
  #block[
    #set enum(numbering: "1.", start: 9)
    + 根据 XYZ
      匹配函数采样波长对于许多场景来说是合理的方法，尽管如果场景中的光源具有高度峰值的光谱（例如，许多荧光灯），则通过根据光源的光谱分布采样波长可能会减少误差。实现这种方法，并使用各种光谱发射剖面将结果与
      `pbrt`
      当前的波长采样实现进行比较。在最佳情况下与最差情况下，替代采样策略在多大程度上有帮助？您能否通过应用多重重要性采样进一步改善结果？
  ]
]

#parec[
  #block[
    #set enum(numbering: "1.", start: 10)
    + The
      #link("../Light_Sources/Light_Sampling.html#BVHLightSampler")[`BVHLightSampler`]
      is missing a number of features in the BVH sampling scheme described
      by Conty Estevez and Kulla (2018), including an importance factor
      specialized for participating media and adaptive splitting, where
      multiple lights may be returned from the sampling operation when it is
      difficult to determine which child node is a better choice at the
      upper levels of the tree. Read their paper and improve `pbrt`'s
      implementation. What is the change in Monte Carlo efficiency? Does the
      reduction in error justify the increase in computation?
  ]
][
  #block[
    #set enum(numbering: "1.", start: 10)
    + #link("../Light_Sources/Light_Sampling.html#BVHLightSampler")[`BVHLightSampler`]
      在 Conty Estevez 和 Kulla（2018）描述的 BVH
      采样方案中缺少许多功能，包括专门用于参与介质的重要性因子和自适应拆分，当难以确定哪个子节点在树的上层是更好的选择时，采样操作可能会返回多个光源。阅读他们的论文并改进
      `pbrt`
      的实现。蒙特卡罗效率的变化有多大？误差的减少是否证明了计算量的增加？
  ]
]

#parec[
  #block[
    #set enum(numbering: "1.", start: 11)
    + Another shortcoming of the current
      #link("../Light_Sources/Light_Sampling.html#BVHLightSampler")[`BVHLightSampler`]
      implementation is that it does not account for the BSDF at the
      reference point but instead effectively assumes a diffuse surface.
      Read the paper by Liu et al.~(2019b) and improve the BVH light
      sampler's implementation by using their approach to account for this
      factor. Measure the change in MSE for a variety of scenes with this
      improvement.
  ]
][
  #block[
    #set enum(numbering: "1.", start: 11)
    + 当前
      #link("../Light_Sources/Light_Sampling.html#BVHLightSampler")[`BVHLightSampler`]
      实现的另一个缺点是它不考虑参考点的
      BSDF，而是有效地假设为漫反射表面。阅读 Liu
      等人（2019b）的论文，并通过使用他们的方法考虑这一因素来改进 BVH
      光采样器的实现。测量这种改进对各种场景的均方误差的变化。
  ]
]


