#import "../template.typ": parec, ez_caption, source-cite

== #ez_caption[Exercises][习题]

#parec[
  1. ② Some types of cameras expose the film by sliding a rectangular slit across the film. This leads to interesting effects when objects are moving in a different direction from the exposure slit (Glassner #source-cite("Glassner1999"); Stephenson #source-cite("Stephenson07")). Furthermore, most digital cameras read out pixel values from scanlines in succession over a period of a few milliseconds; this leads to rolling shutter artifacts, which have similar visual characteristics. Modify the way that time samples are generated in one or more of the camera implementations in this chapter to model such effects. Render images with moving objects that clearly show the effect of accounting for this issue.
][
  1. ② 某些相机通过让矩形狭缝扫过胶片来曝光。当物体运动方向与曝光狭缝的移动方向不同时，会产生有趣的效果（Glassner #source-cite("Glassner1999")；Stephenson #source-cite("Stephenson07")）。此外，多数数码相机会在几毫秒内依次读取各扫描线的像素值，造成视觉特征相似的卷帘快门伪影。修改本章一种或多种相机实现中时间样本的生成方式，以模拟这些效应。渲染包含运动物体的图像，清楚展示考虑这一因素后的效果。
]

#parec[
  2. ② Write an application that loads images rendered by the `SphericalCamera` and uses texture mapping to apply them to a sphere centered at the eyepoint such that they can be viewed interactively. The user should be able to freely change the viewing direction. If the correct texture-mapping function is used for generating texture coordinates on the sphere, the image generated by the application will appear as if the viewer was at the camera's location in the scene when it was rendered, thus giving the user the ability to interactively look around the scene.
][
  2. ② 编写一个应用程序，加载 `SphericalCamera` 渲染的图像，并用纹理映射将它们贴到以视点为中心的球面上，供用户交互查看。用户应能自由改变观察方向。如果球面的纹理坐标生成方式正确，应用程序的图像看起来就像观察者位于原渲染时的相机位置，从而可以交互地环顾场景。
]

#parec[
  3. ② Focal stack rendering: A focal stack is a series of images of a fixed scene where the camera is focused at a different distance for each image. Hasinoff and Kutulakos (#source-cite("Hasinoff2011")) and Jacobs et al. (#source-cite("Jacobs2012")) introduced a number of applications of focal stacks, including freeform depth of field, where the user can specify arbitrary depths that are in focus, achieving effects not possible with traditional optics. Render focal stacks with `pbrt` and write an interactive tool to control focus effects with them.
][
  3. ② 焦点堆栈渲染：焦点堆栈是一组固定场景的图像，每幅图像采用不同的对焦距离。Hasinoff 和 Kutulakos（#source-cite("Hasinoff2011")）以及 Jacobs 等人（#source-cite("Jacobs2012")）介绍了多种应用，包括自由形状景深：用户可以指定任意深度处清晰对焦，得到传统光学无法实现的效果。用 `pbrt` 渲染焦点堆栈，并编写交互工具，用它们控制对焦效果。
]

#parec[
  4. ③ Light field camera: Ng et al. (#source-cite("Ng2005")) discussed the physical design and applications of a camera that captures small images of the exit pupil across the film, rather than averaging the radiance over the entire exit pupil at each pixel, as conventional cameras do. Such a camera captures a representation of the light field—the spatially and directionally varying distribution of radiance arriving at the camera sensor. By capturing the light field, a number of interesting operations are possible, including refocusing photographs after they have been taken. Read Ng et al.'s paper and implement a `Camera` in `pbrt` that captures the light field of a scene. Write a tool to allow users to interactively refocus these light fields.
][
  4. ③ 光场相机：Ng 等人（#source-cite("Ng2005")）讨论了一种相机的物理设计及应用。这种相机在胶片各处记录出瞳的小幅图像，而不是像普通相机那样，在每个像素处对整个出瞳上的辐亮度取平均。它由此记录光场，即到达相机传感器的辐亮度随空间位置与方向变化的分布。获取光场后，可以进行许多有趣的操作，例如在拍摄完成后重新对焦。阅读 Ng 等人的论文，在 `pbrt` 中实现能够捕获场景光场的 `Camera`，并编写工具让用户交互地对这些光场重新对焦。
]

#parec[
  5. ③ The Cameras in this chapter place the film at the center of and perpendicular to the optical axis. While this is the most common configuration of actual cameras, interesting effects can be achieved by adjusting the film's placement with respect to the lens system. For example, the plane of focus in the current implementation is always perpendicular to the optical axis; if the film plane (or the lens system) is tilted so that the film is not perpendicular to the optical axis, then the plane of focus is no longer perpendicular to the optical axis. (This can be useful for landscape photography, for example, where aligning the plane of focus with the ground plane allows greater depth of field even with larger apertures.) Alternatively, the film plane can be shifted so that it is not centered on the optical axis; this shift can be used to keep the plane of focus aligned with a very tall object, for example. Modify the `PerspectiveCamera` to allow one or both of these adjustments and render images showing the result. (You may find Kensler's (#source-cite("Kensler2021")) chapter useful.)
][
  5. ③ 本章的相机让胶片以光轴为中心，并与光轴垂直。虽然这是实际相机最常见的配置，调整胶片相对于镜头系统的位置也能产生有趣的效果。例如，当前实现的对焦平面始终垂直于光轴；如果倾斜胶片平面或镜头系统，使胶片不再垂直于光轴，对焦平面也就不再垂直于光轴。（这对风景摄影很有用：让对焦平面与地面重合，即使使用较大光圈也能获得较大景深。）还可以平移胶片平面，使其不再以光轴为中心；例如，可以借此使对焦平面保持与很高的物体对齐。修改 `PerspectiveCamera`，支持这两种调整中的一种或两种，并渲染图像展示结果。（Kensler（#source-cite("Kensler2021")）的章节可能有帮助。）
]

#parec[
  6. ② The clamping approach used to suppress outlier sample values in the `RGBFilm` and `GBufferFilm` is a heavy-handed solution that can cause a significant amount of energy loss in the image. (Consider, for example, pixels where the sun is directly visible—the radiance along rays in those pixels may be extremely high, though it is not a cause of spiky pixels and should not be clamped.) Implement a more principled solution to this problem such as the technique of Zirr et al. (#source-cite("Zirr2018")). Render images with your implementation and `pbrt`'s current approach and compare the results.
][
  6. ② `RGBFilm` 和 `GBufferFilm` 用限幅抑制离群样本值，这种处理较为粗糙，可能使图像损失大量能量。例如，直接看到太阳的像素，其射线上的辐亮度可能极高，但这并非异常亮点造成的，不应被限幅。为这个问题实现一种依据更充分的方法，例如 Zirr 等人（#source-cite("Zirr2018")）的技术。分别用新实现和 `pbrt` 当前方法渲染图像，比较结果。
]

#parec[
  7. ② Investigate the sources of noise in camera sensors and mathematical models to simulate them. Then, modify the `PixelSensor` class to model the effect of noise. In addition to shot noise, which depends on the number of photons reaching each pixel, you may also want to model factors like read noise and dark noise, which are independent of the number of photons. Render images that exhibit noise and show the effect of different types of it as exposure time varies.
][
  7. ② 研究相机传感器中的噪声来源及其数学模型，然后修改 `PixelSensor` 来模拟噪声。除了依赖各像素接收光子数的散粒噪声，还可以考虑与光子数无关的读出噪声和暗噪声。渲染含噪声的图像，展示不同类型噪声随曝光时间变化的效果。
]

#parec[
  8. ② Because they are based on floating-point addition, which is not associative, the `AddSplat()` methods implemented in this chapter do not live up to `pbrt`'s goal of producing deterministic output: if different threads add splats to the same pixel in a different order over multiple runs of `pbrt`, the final image may differ. An alternative implementation might allocate a separate buffer for each thread's splats and then sum the buffers at the end of rendering, which would be deterministic but would incur a memory cost proportional to the number of threads. Either implement that approach or come up with another one to address this issue and implement it in `pbrt`. Measure the memory and performance overhead of your approach as well as how often the current implementation is non-deterministic. Is the current implementation defensible?
][
  8. ② 浮点加法不满足结合律，因此本章基于浮点加法的 `AddSplat()` 实现未能完全达到 `pbrt` 输出确定性结果的目标：多次运行时，如果不同线程以不同顺序向同一像素添加 splat，最终图像就可能不同。一种替代实现是为每个线程的 splat 分配独立缓冲区，并在渲染结束时对缓冲区求和；这能保证确定性，但内存开销与线程数成正比。实现这一方法，或提出并实现另一种解决方案。测量其内存与性能开销，以及当前实现出现非确定性结果的频率。当前的实现是否有其合理性？
]

#parec[
  9. ③ Image-based rendering is the general name for a set of techniques that use one or more images of a scene to synthesize new images from viewpoints different from the original ones. One such approach is light field rendering, where a set of images from a densely spaced set of positions is used—as described by Levoy and Hanrahan (#source-cite("Levoy96")) and Gortler et al. (#source-cite("Gortler96")). Read these two papers on light fields, and modify `pbrt` to directly generate light fields of scenes, without requiring that the renderer be run multiple times, once for each camera position. It will probably be necessary to write a specialized `Camera`, `Sampler`, and `Film` to do this. Also, write an interactive light field viewer that loads light fields generated by your implementation and that generates new views of the scene.
][
  9. ③ 基于图像的渲染泛指用场景的一幅或多幅图像，从不同于原来的视点合成新图像的技术。其中一种是光场渲染，它使用一组在空间中密集分布的位置上拍摄的图像，参见 Levoy 和 Hanrahan（#source-cite("Levoy96")）及 Gortler 等人（#source-cite("Gortler96")）。阅读这两篇论文，修改 `pbrt`，使其直接生成场景光场，而不必为每个相机位置分别运行一次渲染器。这可能需要专门实现 `Camera`、`Sampler` 和 `Film`。另编写一个交互式光场查看器，加载新实现生成的光场，并生成场景的新视图。
]
