#import "../template.typ": parec


= Sampling and reconstruction
<sampling-and-reconstruction>


#figure(
  image("../pbr-book-website/4ed/openers/checkerboard-ref.png", width: 100%),
)

#parec[
  Although the final output of a renderer is generally a 2D grid of colored pixels, incident radiance is actually a continuous function defined over the film plane. The manner in which the discrete pixel values are computed from this continuous function can noticeably affect the quality of the final image generated by the renderer; if this process is not performed carefully, artifacts will be present. Conversely, if it is performed well, a relatively small amount of additional computation to this end can substantially improve the quality of the rendered images. We have thus far approached this topic from the perspective of Monte Carlo integration, though other viewpoints can also give useful insight.
][
  尽管渲染器的最终输出通常是一个二维的彩色像素网格，但入射光辐射实际上是在胶片平面上定义的连续函数。 从这个连续函数计算离散像素值的方式可以显著影响渲染器生成的最终图像的质量；如果这个过程不够仔细，就可能出现伪影。 相反，如果执行得当，较少量的额外计算就可以显著提高渲染图像的质量。 在此之前，我们从蒙特卡罗积分的角度来探讨这个话题，尽管其他观点也可以提供有用的见解。
]


#parec[
  This chapter starts by introducing sampling theory—the theory of taking discrete sample values from functions defined over continuous domains and then using those samples to reconstruct new functions that are similar to the original. In pbrt, integration is more often the goal than reconstruction is, though we will see that Fourier analysis—the foundation of sampling theory—also provides insight about error in Monte Carlo integration. We discuss those connections as well as other approaches for evaluating the quality of sampling algorithms in the second section of this chapter.
][
  本章首先介绍采样理论——从定义在连续域上的函数中获取离散样本值的理论，然后使用这些样本重建与原始函数相似的新函数。 在pbrt中，积分比重建更常是目标，尽管我们将看到傅里叶分析（Fourier分析）——采样理论的基础——也提供了关于蒙特卡罗积分误差的见解。 在本章的第二部分，我们讨论这些联系以及评估采样算法质量的其他方法。
]

#parec[
  With these ideas in hand, the implementations of six Samplers make up the bulk of this chapter. They span a wide variety of approaches to the sampling problem. The chapter concludes with the Filter class, which determines how multiple samples near each pixel are blended together to compute the final pixel value. Both of pbrt's Film implementations use these filters to accumulate image sample contributions into pixels of images.
][
  有了这些想法，本章的主要内容是六个采样器的实现。 它们展示了采样问题的多种方法。 本章以滤波器类结束，该类决定了如何将每个像素附近的多个样本混合在一起以计算出最终的像素值。 pbrt的两个Film实现都使用这些滤波器将图像样本贡献积累到图像的像素中。
]